#!/usr/bin/env bash

typ=$(nmcli connection show | awk 'NR==2 {print $3}')
device=$(nmcli connection show | awk 'NR==2 {print $NF}')
ssid=$(nmcli connection show | awk 'NR==2 {print $1}')

non=0
quality=""

case $typ in
  "wifi")
    quality=$(iwconfig $device | grep "quality" -i | sed 's/=/ /g' | awk '{print $3}')
    ;;
  "ethernet")
    quality=$(iwconfig $device | grep "quality" -i | sed 's/=/ /g' | awk '{print $3}')
    ;;
  *)
    echo "no"
    exit
    ;;
esac

echo $ssid
echo $quality
