import:
  # Colors
  - ~/.config/alacritty/colors.yml

font:
  normal:
    family: MesloLGS NF
    #family: Meslo LG S Nerd Font Mono
    #family: FantasqueSansMono Nerd Font
    #family: Fira Code
    style: Regular
  size: 9
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

cursor:
  style:
    blinking: On
  blink_interval: 500

draw_bold_text_with_bright_colors: true

url:
  launcher: xdg-open

window:
  opacity: 1
  padding:
    x: 8
    y: 8
  #decoration: full

bell:
  animation: EaseOutExpo
  color: '0xffffff'
  duration: 0
env:
  WINIT_X11_SCALE_FACTOR: "1.0"

#key_bindings:
  #- { key: N,   mode: Search|Vi, action: SearchFocusNext }
  #- { key: N,                           mode: Vi|~Search, action: SearchNext              }
  #- { key: N,      mods: Shift,         mode: Vi|~Search, action: SearchPrevious          }
