#!/bin/zsh

ZINIT_HOME="${HOME}/.local/share/zinit/zinit.git"
if [ ! -d "$ZINIT_HOME" ]; then
   mkdir -p "$(dirname $ZINIT_HOME)"
   git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

source "${ZINIT_HOME}/zinit.zsh"

zi light zsh-users/zsh-completions
zi light zsh-users/zsh-autosuggestions
zi light zsh-users/zsh-syntax-highlighting

zi light lukechilds/zsh-better-npm-completion
zi light zsh-users/zsh-history-substring-search

zi snippet PZTM::completion
zi snippet PZTM::history
zi snippet PZTM::directory
zi snippet PZTM::history-substring-search

zi snippet OMZP::git
zi snippet OMZP::brew
zi snippet OMZP::sudo

# Load completions
autoload -Uz compinit && compinit

zinit ice atload"zpcdreplay" atclone"./zplug.zsh" atpull"%atclone"
zinit light g-plane/pnpm-shell-completion

zi ice as"completion"
zi snippet OMZP::fd/_fd

zi ice as"completion"
zi snippet OMZP::ripgrep/_ripgrep

zinit light Aloxaf/fzf-tab

if type vivid &> /dev/null
then
  export LS_COLORS="$(vivid generate gruvbox)"
  zstyle ":completion:*" list-colors ${(s.:.)LS_COLORS}
fi

zstyle ":completion:*" menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

bindkey -v

source ~/.zsh-syntax
source ~/.zsh-alias

if type brew &>/dev/null
then
  source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
  source /opt/homebrew/opt/chruby/share/chruby/auto.sh
else
  source /usr/local/share/chruby/chruby.sh
  source /usr/local/share/chruby/auto.sh
fi
chruby ruby-3.2.2

zinit cdreplay -q

eval "$(starship init zsh)"
eval "$(fzf --zsh)"
eval "$(zoxide init zsh --cmd=zz)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
