#!/bin/zsh

alias ls="ls --color"
alias ll="ls --color -l"
alias clifm="clifm --lscolors"

alias libreoffice="/Applications/LibreOffice.app/Contents/MacOS/soffice"
alias playit="/Applications/playit.app/Contents/MacOS/playit"

function docxtopdf() {
  libreoffice --headless --convert-to pdf --outdir . $1
}

