#!/bin/zsh

typeset -U path

if [ -d "$HOME/.cargo" ]; then
  source "$HOME/.cargo/env"
fi

export VISUAL=nvim
export EDITOR=nvim
# pnpm
export PNPM_HOME="/Users/jezerm/Library/pnpm"
path=($PNPM_HOME $path)
# pnpm end

export COMPOSER_BIN="/Users/jezerm/.composer/vendor/bin"
path=($COMPOSER_BIN $path)

path=("/usr/local/mysql/bin/" $path)
path=("$HOME/.local/bin/" $path)

path=("/opt/homebrew/bin/" $path)
path=("/opt/homebrew/opt/coreutils/libexec/gnubin/" $path)
path=("/opt/homebrew/opt/ruby/bin/" $path)
path=("/opt/homebrew/lib/ruby/gems/3.2.0/bin/" $path)

set HOMEBREW_NO_AUTO_UPDATE
