#!/bin/zsh

ZINIT_HOME="${HOME}/.local/share/zinit/zinit.git"
if [ ! -d "$ZINIT_HOME" ]; then
   mkdir -p "$(dirname $ZINIT_HOME)"
   git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

source "${ZINIT_HOME}/zinit.zsh"

zi light zsh-users/zsh-autosuggestions
zi light zsh-users/zsh-syntax-highlighting

zi light lukechilds/zsh-better-npm-completion
zi light zsh-users/zsh-history-substring-search

zi snippet PZTM::completion
zi snippet PZTM::history
zi snippet PZTM::directory
zi snippet PZTM::history-substring-search

zi snippet OMZP::git
zi snippet OMZP::brew
zi snippet OMZP::sudo

export NVM_COMPLETION=true
export NVM_SYMLINK_CURRENT="true"
zinit wait lucid light-mode for lukechilds/zsh-nvm

zinit ice atload"zpcdreplay" atclone"./zplug.zsh" atpull"%atclone"
zinit light g-plane/pnpm-shell-completion

zi ice as"completion"
zi snippet OMZP::fd/_fd

zi ice as"completion"
zi snippet OMZP::ripgrep/_ripgrep

zinit light Aloxaf/fzf-tab

zi wait lucid atload"zicompinit; zicdreplay" blockf for \
  zsh-users/zsh-completions

if type vivid &> /dev/null
then
  export LS_COLORS="$(vivid generate gruvbox)"
  zstyle ":completion:*" list-colors ${(s.:.)LS_COLORS}
fi

zstyle ":completion:*" menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

bindkey -v

source ~/.zsh-syntax
source ~/.zsh-alias

eval "$(starship init zsh)"
eval "$(fzf --zsh)"
eval "$(zoxide init zsh --cmd=zz)"
eval "$(rbenv init - zsh)"
