[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.cursor]
background = "#ebdbb2"
text = "#282828"

[colors.hints.end]
background = "#ebdbb2"
foreground = "#EE8739"

[colors.hints.start]
background = "#ebdbb2"
foreground = "#EE8739"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.selection]
background = "#655c55"
text = "#282828"
